const array = [
  { letra: "a", isDisabled: true },
  { letra: "b", isDisabled: true },
  { letra: "c", isDisabled: true },
  { letra: "d", isDisabled: true },
  { letra: "e", isDisabled: true },
  { letra: "f", isDisabled: true },
  { letra: "g", isDisabled: true },
  { letra: "h", isDisabled: true },
  { letra: "i", isDisabled: true },
  { letra: "j", isDisabled: true },
  { letra: "k", isDisabled: true },
  { letra: "l", isDisabled: true },
  { letra: "m", isDisabled: true },
  { letra: "n", isDisabled: true },
  { letra: "o", isDisabled: true },
  { letra: "p", isDisabled: true },
  { letra: "q", isDisabled: true },
  { letra: "r", isDisabled: true },
  { letra: "s", isDisabled: true },
  { letra: "t", isDisabled: true },
  { letra: "u", isDisabled: true },
  { letra: "v", isDisabled: true },
  { letra: "x", isDisabled: true },
  { letra: "w", isDisabled: true },
  { letra: "y", isDisabled: true },
  { letra: "z", isDisabled: true },
];

export default array;
